version: "3.9"

services:
  backend:
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_TYPE=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=SweetControl
      - DB_DATABASE=sweetcontrol
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

  frontend:
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
      - WATCHPACK_POLLING=true
